version: '2'

services:
  app:
    image: 'tenpo-challenge:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tenpo_challenge_data
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - EXTERNAL_SERVICE_URL=http://percentage-ms:8080
      - EXTERNAL_SERVICE_URN=/percentage
      - SPRING_APPLICATION_CONNECTION_TIME_OUT=60
      - SPRING_APPLICATION_READ_TIME_OUT=60
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_DATA_REDIS_TIMEOUT=6000
      - SPRING_RETRY_CONFIG_BACK_OF_PERIOD=1000
      - SPRING_RETRY_CONFIG_MAX_ATTEMPTS=3
      - SPRING_APPLICATION_ASYNC_POOL_SIZE=5
      - SPRING_APPLICATION_ASYNC_MAX_POOL_SIZE=10
      - SPRING_APPLICATION_ASYNC_QUEUE_SIZE=25
    ports:
      - '9009:9009'

  percentage-ms:
    image: 'percentage-ms:latest'
    build:
      context: .
    container_name: percentage-ms
    ports:
      - '8080:8080'
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tenpo_challenge_data
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
